[package]
name = "ltcd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
ben = { git = "https://github.com/rana/ben.git", version = "0.3.0" }

[profile.test]
opt-level = 3